"""baseline schema

The PARIVART schema as deployed at the end of Phase 6. This revision exists so that an
already-running database can be stamped at a known point and moved forward from there;
on an empty database it builds the whole schema from scratch.

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-09-29 17:05:02.321072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001_baseline'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('regulatory_authorities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('jurisdiction', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_authorities_id'), 'regulatory_authorities', ['id'], unique=False)
    op.create_index(op.f('ix_regulatory_authorities_short_name'), 'regulatory_authorities', ['short_name'], unique=True)
    op.create_table('markets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('regulatory_jurisdiction', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'PLANNED', name='marketstatus', native_enum=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_markets_id'), 'markets', ['id'], unique=False)
    op.create_index(op.f('ix_markets_organization_id'), 'markets', ['organization_id'], unique=False)
    op.create_table('processes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processes_id'), 'processes', ['id'], unique=False)
    op.create_index(op.f('ix_processes_organization_id'), 'processes', ['organization_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('product_code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('sub_category', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', 'DRAFT', name='productstatus', native_enum=False), nullable=True),
    sa.Column('regulatory_class', sa.String(length=100), nullable=True),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_organization_id'), 'products', ['organization_id'], unique=False)
    op.create_index(op.f('ix_products_product_code'), 'products', ['product_code'], unique=True)
    op.create_table('regulatory_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('authority_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('jurisdiction', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('source_type', sa.Enum('RSS', 'API', 'WEB_SERVICE', 'HTML', 'DOCUMENT', name='sourcetype', native_enum=False), nullable=False),
    sa.Column('connector_type', sa.Enum('RSS', 'API', 'WEB_SERVICE', 'HTML', 'DOCUMENT', name='connectortype', native_enum=False), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('schedule', sa.String(length=100), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['authority_id'], ['regulatory_authorities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_sources_authority_id'), 'regulatory_sources', ['authority_id'], unique=False)
    op.create_index(op.f('ix_regulatory_sources_id'), 'regulatory_sources', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_id'), 'audit_events', ['id'], unique=False)
    op.create_index(op.f('ix_audit_events_organization_id'), 'audit_events', ['organization_id'], unique=False)
    op.create_table('controls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('process_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('QUALITY', 'SAFETY', 'REGULATORY', 'CYBERSECURITY', 'DATA', 'MANUFACTURING', 'LABELING', 'CLINICAL', 'RISK', 'OTHER', name='controlcategory', native_enum=False), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DRAFT', name='controlstatus', native_enum=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_controls_id'), 'controls', ['id'], unique=False)
    op.create_index(op.f('ix_controls_organization_id'), 'controls', ['organization_id'], unique=False)
    op.create_index(op.f('ix_controls_process_id'), 'controls', ['process_id'], unique=False)
    op.create_index(op.f('ix_controls_product_id'), 'controls', ['product_id'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'PARTIAL', 'FAILED', name='ingestionstatus', native_enum=False), nullable=True),
    sa.Column('documents_discovered', sa.Integer(), nullable=True),
    sa.Column('documents_downloaded', sa.Integer(), nullable=True),
    sa.Column('documents_processed', sa.Integer(), nullable=True),
    sa.Column('documents_failed', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['regulatory_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_id'), 'ingestion_runs', ['id'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_source_id'), 'ingestion_runs', ['source_id'], unique=False)
    op.create_table('product_markets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('market_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'PLANNED', name='marketstatus', native_enum=False), nullable=True),
    sa.Column('launch_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registration_status', sa.String(length=100), nullable=True),
    sa.Column('registration_reference', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_markets_id'), 'product_markets', ['id'], unique=False)
    op.create_index(op.f('ix_product_markets_market_id'), 'product_markets', ['market_id'], unique=False)
    op.create_index(op.f('ix_product_markets_product_id'), 'product_markets', ['product_id'], unique=False)
    op.create_table('registrations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('product_id', sa.String(length=36), nullable=True),
    sa.Column('market_id', sa.String(length=36), nullable=True),
    sa.Column('authority_id', sa.String(length=36), nullable=True),
    sa.Column('registration_number', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'PENDING', 'REJECTED', 'WITHDRAWN', name='registrationstatus', native_enum=False), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['authority_id'], ['regulatory_authorities.id'], ),
    sa.ForeignKeyConstraint(['market_id'], ['markets.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registrations_authority_id'), 'registrations', ['authority_id'], unique=False)
    op.create_index(op.f('ix_registrations_id'), 'registrations', ['id'], unique=False)
    op.create_index(op.f('ix_registrations_market_id'), 'registrations', ['market_id'], unique=False)
    op.create_index(op.f('ix_registrations_organization_id'), 'registrations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_registrations_product_id'), 'registrations', ['product_id'], unique=False)
    op.create_table('regulatory_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('authority_id', sa.String(length=36), nullable=True),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('document_type', sa.Enum('REGULATION', 'GUIDANCE', 'NOTICE', 'SAFETY_ALERT', 'STANDARD', 'AMENDMENT', 'RULE', 'DRAFT', 'FINAL', 'OTHER', name='documenttype', native_enum=False), nullable=True),
    sa.Column('jurisdiction', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('publication_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('processing_status', sa.Enum('DISCOVERED', 'DOWNLOADING', 'DOWNLOADED', 'PARSING', 'PARSED', 'ANALYZING', 'ANALYZED', 'FAILED', name='documentprocessingstatus', native_enum=False), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['authority_id'], ['regulatory_authorities.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['regulatory_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_documents_authority_id'), 'regulatory_documents', ['authority_id'], unique=False)
    op.create_index(op.f('ix_regulatory_documents_id'), 'regulatory_documents', ['id'], unique=False)
    op.create_index(op.f('ix_regulatory_documents_organization_id'), 'regulatory_documents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_regulatory_documents_sha256'), 'regulatory_documents', ['sha256'], unique=True)
    op.create_index(op.f('ix_regulatory_documents_source_id'), 'regulatory_documents', ['source_id'], unique=False)
    op.create_table('regulatory_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('previous_version_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['regulatory_documents.id'], ),
    sa.ForeignKeyConstraint(['previous_version_id'], ['regulatory_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_versions_document_id'), 'regulatory_versions', ['document_id'], unique=False)
    op.create_index(op.f('ix_regulatory_versions_id'), 'regulatory_versions', ['id'], unique=False)
    op.create_index(op.f('ix_regulatory_versions_sha256'), 'regulatory_versions', ['sha256'], unique=False)
    op.create_table('regulatory_changes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('version_id', sa.String(length=36), nullable=True),
    sa.Column('section', sa.String(length=500), nullable=True),
    sa.Column('change_type', sa.Enum('NEW_REQUIREMENT', 'REQUIREMENT_CHANGE', 'DELETED_REQUIREMENT', 'SCOPE_CHANGE', 'DEADLINE_CHANGE', 'LABELING_CHANGE', 'REPORTING_CHANGE', 'PROCESS_CHANGE', 'SAFETY_CHANGE', 'DEFINITION_CHANGE', 'OTHER', name='changetype', native_enum=False), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('previous_text', sa.Text(), nullable=True),
    sa.Column('new_text', sa.Text(), nullable=True),
    sa.Column('source_reference', sa.String(length=500), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('prompt_version', sa.String(length=100), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['regulatory_documents.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['regulatory_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_changes_document_id'), 'regulatory_changes', ['document_id'], unique=False)
    op.create_index(op.f('ix_regulatory_changes_id'), 'regulatory_changes', ['id'], unique=False)
    op.create_index(op.f('ix_regulatory_changes_version_id'), 'regulatory_changes', ['version_id'], unique=False)
    op.create_table('impact_assessments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('regulatory_change_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ANALYZING', 'COMPLETED', 'FAILED', 'REQUIRES_REVIEW', 'REVIEWED', name='impactassessmentstatus', native_enum=False), nullable=True),
    sa.Column('overall_impact_level', sa.Enum('NO_MATCH', 'LOW', 'MEDIUM', 'HIGH', 'POTENTIALLY_AFFECTED', 'REQUIRES_REVIEW', name='impactlevel', native_enum=False), nullable=True),
    sa.Column('overall_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('analysis_version', sa.Integer(), nullable=True),
    sa.Column('engine_version', sa.String(length=50), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=100), nullable=True),
    sa.Column('ai_enrichment_status', sa.Enum('DISABLED', 'SUCCESS', 'RATE_LIMITED', 'TIMEOUT', 'UNAVAILABLE', 'INVALID_RESPONSE', 'AUTH_ERROR', 'PROVIDER_ERROR', name='aienrichmentstatus', native_enum=False), nullable=False),
    sa.Column('ai_enrichment_error', sa.Text(), nullable=True),
    sa.Column('ai_narrative', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['regulatory_change_id'], ['regulatory_changes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impact_assessments_id'), 'impact_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_impact_assessments_organization_id'), 'impact_assessments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_impact_assessments_regulatory_change_id'), 'impact_assessments', ['regulatory_change_id'], unique=False)
    op.create_table('regulatory_obligations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('change_id', sa.String(length=36), nullable=True),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('LABELING', 'MANUFACTURING', 'QUALITY', 'SAFETY', 'REPORTING', 'REGISTRATION', 'SUBMISSION', 'POST_MARKET', 'CLINICAL', 'PACKAGING', 'DATA', 'CYBERSECURITY', 'RECORDKEEPING', 'OTHER', name='obligationcategory', native_enum=False), nullable=False),
    sa.Column('applicability', sa.Text(), nullable=True),
    sa.Column('jurisdiction', sa.String(length=100), nullable=True),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_page', sa.String(length=100), nullable=True),
    sa.Column('source_section', sa.String(length=200), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('prompt_version', sa.String(length=100), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['change_id'], ['regulatory_changes.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['regulatory_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_obligations_change_id'), 'regulatory_obligations', ['change_id'], unique=False)
    op.create_index(op.f('ix_regulatory_obligations_document_id'), 'regulatory_obligations', ['document_id'], unique=False)
    op.create_index(op.f('ix_regulatory_obligations_id'), 'regulatory_obligations', ['id'], unique=False)
    op.create_table('impact_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('impact_assessment_id', sa.String(length=36), nullable=False),
    sa.Column('obligation_id', sa.String(length=36), nullable=True),
    sa.Column('entity_type', sa.Enum('PRODUCT', 'MARKET', 'PROCESS', 'CONTROL', 'REGISTRATION', name='entitytype', native_enum=False), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('impact_level', sa.Enum('NO_MATCH', 'LOW', 'MEDIUM', 'HIGH', 'POTENTIALLY_AFFECTED', 'REQUIRES_REVIEW', name='impactlevel', native_enum=False), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('match_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('match_types', sa.String(length=500), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['impact_assessment_id'], ['impact_assessments.id'], ),
    sa.ForeignKeyConstraint(['obligation_id'], ['regulatory_obligations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impact_items_entity_id'), 'impact_items', ['entity_id'], unique=False)
    op.create_index(op.f('ix_impact_items_id'), 'impact_items', ['id'], unique=False)
    op.create_index(op.f('ix_impact_items_impact_assessment_id'), 'impact_items', ['impact_assessment_id'], unique=False)
    op.create_index(op.f('ix_impact_items_obligation_id'), 'impact_items', ['obligation_id'], unique=False)
    op.create_table('impact_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('impact_assessment_id', sa.String(length=36), nullable=False),
    sa.Column('regulatory_change_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'GENERATED', 'UNDER_REVIEW', 'REVIEWED', 'ARCHIVED', name='impactreportstatus', native_enum=False), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('report_data', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['impact_assessment_id'], ['impact_assessments.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['regulatory_change_id'], ['regulatory_changes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impact_reports_id'), 'impact_reports', ['id'], unique=False)
    op.create_index(op.f('ix_impact_reports_impact_assessment_id'), 'impact_reports', ['impact_assessment_id'], unique=False)
    op.create_index(op.f('ix_impact_reports_organization_id'), 'impact_reports', ['organization_id'], unique=False)
    op.create_index(op.f('ix_impact_reports_regulatory_change_id'), 'impact_reports', ['regulatory_change_id'], unique=False)
    op.create_table('impact_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('impact_assessment_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.Enum('ACCEPTED', 'REJECTED', 'NEEDS_INFO', name='reviewdecision', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['impact_assessment_id'], ['impact_assessments.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_impact_reviews_id'), 'impact_reviews', ['id'], unique=False)
    op.create_index(op.f('ix_impact_reviews_impact_assessment_id'), 'impact_reviews', ['impact_assessment_id'], unique=False)
    op.create_index(op.f('ix_impact_reviews_reviewer_id'), 'impact_reviews', ['reviewer_id'], unique=False)
    op.create_table('actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('impact_item_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'BLOCKED', 'DONE', 'CANCELLED', name='actionstatus', native_enum=False), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['impact_item_id'], ['impact_items.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actions_id'), 'actions', ['id'], unique=False)
    op.create_index(op.f('ix_actions_impact_item_id'), 'actions', ['impact_item_id'], unique=False)
    op.create_index(op.f('ix_actions_organization_id'), 'actions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_actions_owner_id'), 'actions', ['owner_id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('action_id', sa.String(length=36), nullable=True),
    sa.Column('uploaded_by_id', sa.String(length=36), nullable=True),
    sa.Column('filename', sa.String(length=500), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['actions.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_action_id'), 'evidence', ['action_id'], unique=False)
    op.create_index(op.f('ix_evidence_id'), 'evidence', ['id'], unique=False)
    op.create_index(op.f('ix_evidence_organization_id'), 'evidence', ['organization_id'], unique=False)
    op.create_index(op.f('ix_evidence_sha256'), 'evidence', ['sha256'], unique=False)
    op.create_index(op.f('ix_evidence_uploaded_by_id'), 'evidence', ['uploaded_by_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_uploaded_by_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_sha256'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_organization_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_action_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_actions_owner_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_organization_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_impact_item_id'), table_name='actions')
    op.drop_index(op.f('ix_actions_id'), table_name='actions')
    op.drop_table('actions')
    op.drop_index(op.f('ix_impact_reviews_reviewer_id'), table_name='impact_reviews')
    op.drop_index(op.f('ix_impact_reviews_impact_assessment_id'), table_name='impact_reviews')
    op.drop_index(op.f('ix_impact_reviews_id'), table_name='impact_reviews')
    op.drop_table('impact_reviews')
    op.drop_index(op.f('ix_impact_reports_regulatory_change_id'), table_name='impact_reports')
    op.drop_index(op.f('ix_impact_reports_organization_id'), table_name='impact_reports')
    op.drop_index(op.f('ix_impact_reports_impact_assessment_id'), table_name='impact_reports')
    op.drop_index(op.f('ix_impact_reports_id'), table_name='impact_reports')
    op.drop_table('impact_reports')
    op.drop_index(op.f('ix_impact_items_obligation_id'), table_name='impact_items')
    op.drop_index(op.f('ix_impact_items_impact_assessment_id'), table_name='impact_items')
    op.drop_index(op.f('ix_impact_items_id'), table_name='impact_items')
    op.drop_index(op.f('ix_impact_items_entity_id'), table_name='impact_items')
    op.drop_table('impact_items')
    op.drop_index(op.f('ix_regulatory_obligations_id'), table_name='regulatory_obligations')
    op.drop_index(op.f('ix_regulatory_obligations_document_id'), table_name='regulatory_obligations')
    op.drop_index(op.f('ix_regulatory_obligations_change_id'), table_name='regulatory_obligations')
    op.drop_table('regulatory_obligations')
    op.drop_index(op.f('ix_impact_assessments_regulatory_change_id'), table_name='impact_assessments')
    op.drop_index(op.f('ix_impact_assessments_organization_id'), table_name='impact_assessments')
    op.drop_index(op.f('ix_impact_assessments_id'), table_name='impact_assessments')
    op.drop_table('impact_assessments')
    op.drop_index(op.f('ix_regulatory_changes_version_id'), table_name='regulatory_changes')
    op.drop_index(op.f('ix_regulatory_changes_id'), table_name='regulatory_changes')
    op.drop_index(op.f('ix_regulatory_changes_document_id'), table_name='regulatory_changes')
    op.drop_table('regulatory_changes')
    op.drop_index(op.f('ix_regulatory_versions_sha256'), table_name='regulatory_versions')
    op.drop_index(op.f('ix_regulatory_versions_id'), table_name='regulatory_versions')
    op.drop_index(op.f('ix_regulatory_versions_document_id'), table_name='regulatory_versions')
    op.drop_table('regulatory_versions')
    op.drop_index(op.f('ix_regulatory_documents_source_id'), table_name='regulatory_documents')
    op.drop_index(op.f('ix_regulatory_documents_sha256'), table_name='regulatory_documents')
    op.drop_index(op.f('ix_regulatory_documents_organization_id'), table_name='regulatory_documents')
    op.drop_index(op.f('ix_regulatory_documents_id'), table_name='regulatory_documents')
    op.drop_index(op.f('ix_regulatory_documents_authority_id'), table_name='regulatory_documents')
    op.drop_table('regulatory_documents')
    op.drop_index(op.f('ix_registrations_product_id'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_organization_id'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_market_id'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_id'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_authority_id'), table_name='registrations')
    op.drop_table('registrations')
    op.drop_index(op.f('ix_product_markets_product_id'), table_name='product_markets')
    op.drop_index(op.f('ix_product_markets_market_id'), table_name='product_markets')
    op.drop_index(op.f('ix_product_markets_id'), table_name='product_markets')
    op.drop_table('product_markets')
    op.drop_index(op.f('ix_ingestion_runs_source_id'), table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_id'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_controls_product_id'), table_name='controls')
    op.drop_index(op.f('ix_controls_process_id'), table_name='controls')
    op.drop_index(op.f('ix_controls_organization_id'), table_name='controls')
    op.drop_index(op.f('ix_controls_id'), table_name='controls')
    op.drop_table('controls')
    op.drop_index(op.f('ix_audit_events_organization_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_regulatory_sources_id'), table_name='regulatory_sources')
    op.drop_index(op.f('ix_regulatory_sources_authority_id'), table_name='regulatory_sources')
    op.drop_table('regulatory_sources')
    op.drop_index(op.f('ix_products_product_code'), table_name='products')
    op.drop_index(op.f('ix_products_organization_id'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_processes_organization_id'), table_name='processes')
    op.drop_index(op.f('ix_processes_id'), table_name='processes')
    op.drop_table('processes')
    op.drop_index(op.f('ix_markets_organization_id'), table_name='markets')
    op.drop_index(op.f('ix_markets_id'), table_name='markets')
    op.drop_table('markets')
    op.drop_index(op.f('ix_regulatory_authorities_short_name'), table_name='regulatory_authorities')
    op.drop_index(op.f('ix_regulatory_authorities_id'), table_name='regulatory_authorities')
    op.drop_table('regulatory_authorities')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
